import { MovieSection } from "./types";

export const movieSections: MovieSection[] = [
  {
    id: "trending",
    title: "Trending Now",
    movies: [
      {
        id: "1",
        title: "The Night Runner",
        description: "A mysterious vigilante roams the neon-lit city.",
        year: 2023,
        genre: "Action, Thriller",
        rating: 8.2,
        poster: "🦸‍♂️",
        banner: "🌃",
      },
      {
        id: "2",
        title: "Galactic Voyage",
        description: "A crew ventures beyond the stars in search of a new home.",
        year: 2022,
        genre: "Sci-Fi, Adventure",
        rating: 7.9,
        poster: "🚀",
        banner: "🌌",
      },
      {
        id: "3",
        title: "Love in Paris",
        description: "Two strangers find love in the city of lights.",
        year: 2021,
        genre: "Romance, Drama",
        rating: 7.5,
        poster: "💑",
        banner: "🗼",
      },
      {
        id: "4",
        title: "Jungle Quest",
        description: "An explorer faces the wildest challenges in the Amazon.",
        year: 2020,
        genre: "Adventure, Family",
        rating: 7.8,
        poster: "🦧",
        banner: "🌳",
      },
    ],
  },
  {
    id: "top-rated",
    title: "Top Rated",
    movies: [
      {
        id: "5",
        title: "The Last Stand",
        description: "A soldier's final mission to save his homeland.",
        year: 2019,
        genre: "War, Drama",
        rating: 8.7,
        poster: "🪖",
        banner: "🔥",
      },
      {
        id: "6",
        title: "Mystic Falls",
        description: "A detective unravels secrets in a haunted town.",
        year: 2021,
        genre: "Mystery, Horror",
        rating: 8.1,
        poster: "👻",
        banner: "🌫️",
      },
      {
        id: "7",
        title: "Chef's Table",
        description: "A culinary journey across the globe.",
        year: 2022,
        genre: "Documentary, Food",
        rating: 8.5,
        poster: "👨‍🍳",
        banner: "🍽️",
      },
      {
        id: "8",
        title: "Wildlife Wonders",
        description: "Discover the beauty of Earth's creatures.",
        year: 2020,
        genre: "Nature, Documentary",
        rating: 8.3,
        poster: "🦁",
        banner: "🌍",
      },
    ],
  },
  {
    id: "new-releases",
    title: "New Releases",
    movies: [
      {
        id: "9",
        title: "Cyber City",
        description: "A hacker fights for freedom in a digital dystopia.",
        year: 2024,
        genre: "Sci-Fi, Action",
        rating: 7.6,
        poster: "🤖",
        banner: "🌐",
      },
      {
        id: "10",
        title: "Hidden Truths",
        description: "A journalist uncovers a global conspiracy.",
        year: 2024,
        genre: "Thriller, Drama",
        rating: 7.8,
        poster: "🕵️‍♀️",
        banner: "📰",
      },
      {
        id: "11",
        title: "The Big Score",
        description: "A team plans the ultimate heist.",
        year: 2024,
        genre: "Crime, Action",
        rating: 7.7,
        poster: "💰",
        banner: "🏦",
      },
      {
        id: "12",
        title: "Dreamscape",
        description: "A journey through surreal worlds of the mind.",
        year: 2024,
        genre: "Fantasy, Adventure",
        rating: 7.9,
        poster: "🦄",
        banner: "🌈",
      },
    ],
  },
];
